import type { NextPage } from 'next'
import Head from 'next/head'
import { ChangeEvent, useCallback, useEffect, useRef, useState } from 'react'
import styles from '../styles/Home.module.css'
import { ImageCard } from 'components/ImageCard'
import { List } from 'components/List'
import domtoimage from 'dom-to-image'
import { saveAs } from 'file-saver'

const Home: NextPage = () => {
  const listRef = useRef<HTMLDivElement>(null)

  const clickSaveBtn = () => {
    if (listRef.current) {
      domtoimage.toBlob(listRef.current).then(function (blob: any) {
        saveAs(blob, 'image.png')
      })
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <main className="p-4 min-w-[90%]">
          <h3 className="font-bold text-center text-2xl m-4">첫인상/현인상 만들기</h3>
          <div className="flex flex-nowrap space-x-4 w-full mb-3">
            <div className="w-1/3 text-center">사람</div>
            <div className="w-1/3 text-center">첫인상</div>
            <div className="w-1/3 text-center">현인상</div>
          </div>
          <div ref={listRef}>
            <List />
          </div>

          <div className="flex flex-col mt-20 justify-center items-center">
            <button className="block border rounded-full p-2 m-2 w-32">ADD</button>
            <button className="block border rounded-full p-2 m-2 w-32" onClick={clickSaveBtn}>
              Save To Image
            </button>
          </div>
        </main>
      </div>
    </div>
  )
}

export default Home
